# Generated by Django 3.1 on 2021-06-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='photos/products', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Activado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cash',
            field=models.IntegerField(verbose_name='Precio Efectivo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_credit',
            field=models.IntegerField(verbose_name='Precio Tarjeta de Credito'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_naame',
            field=models.CharField(max_length=200, unique=True, verbose_name='Titulo'),
        ),
    ]
