# Generated by Django 3.1 on 2021-07-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210708_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '1. Carrito', 'verbose_name_plural': '1. Carritos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': '2. Item por Carrito', 'verbose_name_plural': '2. Item por Carritos'},
        ),
    ]
